# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password: Mateobeccan2002

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDRmNzhhZTQ0ODZiZjYwODkxZjEzMGEwMTIzNDk0NGRhZmViN2IwNjAwMTY1MjU2NWRlNDY1MzczZjJmNTQ1ZWYzM2Q4OWI4OGJiYmM0MTE2NDEwY2Q0YzFlZWM0NzE0ZTAyNmY0N2Y2NThjZmQyZDUwNDUyOTc1NzgzYTY5NDE=
