package com.concesionaria.app.domain;

import static com.concesionaria.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AutoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoAllPropertiesEquals(Auto expected, Auto actual) {
        assertAutoAutoGeneratedPropertiesEquals(expected, actual);
        assertAutoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoAllUpdatablePropertiesEquals(Auto expected, Auto actual) {
        assertAutoUpdatableFieldsEquals(expected, actual);
        assertAutoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoAutoGeneratedPropertiesEquals(Auto expected, Auto actual) {
        assertThat(actual)
            .as("Verify Auto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoUpdatableFieldsEquals(Auto expected, Auto actual) {
        assertThat(actual)
            .as("Verify Auto relevant properties")
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getCondicion()).as("check condicion").isEqualTo(expected.getCondicion()))
            .satisfies(a -> assertThat(a.getFechaFabricacion()).as("check fechaFabricacion").isEqualTo(expected.getFechaFabricacion()))
            .satisfies(a -> assertThat(a.getFechaIngreso()).as("check fechaIngreso").isEqualTo(expected.getFechaIngreso()))
            .satisfies(a -> assertThat(a.getKm()).as("check km").isEqualTo(expected.getKm()))
            .satisfies(a -> assertThat(a.getPatente()).as("check patente").isEqualTo(expected.getPatente()))
            .satisfies(a ->
                assertThat(a.getPrecio()).as("check precio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrecio())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoUpdatableRelationshipsEquals(Auto expected, Auto actual) {
        assertThat(actual)
            .as("Verify Auto relationships")
            .satisfies(a -> assertThat(a.getMarca()).as("check marca").isEqualTo(expected.getMarca()))
            .satisfies(a -> assertThat(a.getModelo()).as("check modelo").isEqualTo(expected.getModelo()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getMotor()).as("check motor").isEqualTo(expected.getMotor()))
            .satisfies(a -> assertThat(a.getMoneda()).as("check moneda").isEqualTo(expected.getMoneda()));
    }
}
