package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarroceriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarroceriaAllPropertiesEquals(Carroceria expected, Carroceria actual) {
        assertCarroceriaAutoGeneratedPropertiesEquals(expected, actual);
        assertCarroceriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarroceriaAllUpdatablePropertiesEquals(Carroceria expected, Carroceria actual) {
        assertCarroceriaUpdatableFieldsEquals(expected, actual);
        assertCarroceriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarroceriaAutoGeneratedPropertiesEquals(Carroceria expected, Carroceria actual) {
        assertThat(actual)
            .as("Verify Carroceria auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarroceriaUpdatableFieldsEquals(Carroceria expected, Carroceria actual) {
        assertThat(actual)
            .as("Verify Carroceria relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarroceriaUpdatableRelationshipsEquals(Carroceria expected, Carroceria actual) {
        // empty method
    }
}
