package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CombustibleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustibleAllPropertiesEquals(Combustible expected, Combustible actual) {
        assertCombustibleAutoGeneratedPropertiesEquals(expected, actual);
        assertCombustibleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustibleAllUpdatablePropertiesEquals(Combustible expected, Combustible actual) {
        assertCombustibleUpdatableFieldsEquals(expected, actual);
        assertCombustibleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustibleAutoGeneratedPropertiesEquals(Combustible expected, Combustible actual) {
        assertThat(actual)
            .as("Verify Combustible auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustibleUpdatableFieldsEquals(Combustible expected, Combustible actual) {
        assertThat(actual)
            .as("Verify Combustible relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustibleUpdatableRelationshipsEquals(Combustible expected, Combustible actual) {
        // empty method
    }
}
