package com.concesionaria.app.domain;

import static com.concesionaria.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ComprobanteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComprobanteAllPropertiesEquals(Comprobante expected, Comprobante actual) {
        assertComprobanteAutoGeneratedPropertiesEquals(expected, actual);
        assertComprobanteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComprobanteAllUpdatablePropertiesEquals(Comprobante expected, Comprobante actual) {
        assertComprobanteUpdatableFieldsEquals(expected, actual);
        assertComprobanteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComprobanteAutoGeneratedPropertiesEquals(Comprobante expected, Comprobante actual) {
        assertThat(actual)
            .as("Verify Comprobante auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComprobanteUpdatableFieldsEquals(Comprobante expected, Comprobante actual) {
        assertThat(actual)
            .as("Verify Comprobante relevant properties")
            .satisfies(a -> assertThat(a.getNumeroComprobante()).as("check numeroComprobante").isEqualTo(expected.getNumeroComprobante()))
            .satisfies(a -> assertThat(a.getFechaEmision()).as("check fechaEmision").isEqualTo(expected.getFechaEmision()))
            .satisfies(a ->
                assertThat(a.getImporteNeto())
                    .as("check importeNeto")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getImporteNeto())
            )
            .satisfies(a ->
                assertThat(a.getImpuesto()).as("check impuesto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getImpuesto())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertComprobanteUpdatableRelationshipsEquals(Comprobante expected, Comprobante actual) {
        assertThat(actual)
            .as("Verify Comprobante relationships")
            .satisfies(a -> assertThat(a.getVenta()).as("check venta").isEqualTo(expected.getVenta()))
            .satisfies(a -> assertThat(a.getTipoComprobante()).as("check tipoComprobante").isEqualTo(expected.getTipoComprobante()))
            .satisfies(a -> assertThat(a.getMoneda()).as("check moneda").isEqualTo(expected.getMoneda()));
    }
}
