package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CondicionIvaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCondicionIvaAllPropertiesEquals(CondicionIva expected, CondicionIva actual) {
        assertCondicionIvaAutoGeneratedPropertiesEquals(expected, actual);
        assertCondicionIvaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCondicionIvaAllUpdatablePropertiesEquals(CondicionIva expected, CondicionIva actual) {
        assertCondicionIvaUpdatableFieldsEquals(expected, actual);
        assertCondicionIvaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCondicionIvaAutoGeneratedPropertiesEquals(CondicionIva expected, CondicionIva actual) {
        assertThat(actual)
            .as("Verify CondicionIva auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCondicionIvaUpdatableFieldsEquals(CondicionIva expected, CondicionIva actual) {
        assertThat(actual)
            .as("Verify CondicionIva relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCondicionIvaUpdatableRelationshipsEquals(CondicionIva expected, CondicionIva actual) {
        // empty method
    }
}
