package com.concesionaria.app.domain;

import static com.concesionaria.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CotizacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCotizacionAllPropertiesEquals(Cotizacion expected, Cotizacion actual) {
        assertCotizacionAutoGeneratedPropertiesEquals(expected, actual);
        assertCotizacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCotizacionAllUpdatablePropertiesEquals(Cotizacion expected, Cotizacion actual) {
        assertCotizacionUpdatableFieldsEquals(expected, actual);
        assertCotizacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCotizacionAutoGeneratedPropertiesEquals(Cotizacion expected, Cotizacion actual) {
        assertThat(actual)
            .as("Verify Cotizacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCotizacionUpdatableFieldsEquals(Cotizacion expected, Cotizacion actual) {
        assertThat(actual)
            .as("Verify Cotizacion relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a ->
                assertThat(a.getValorCompra())
                    .as("check valorCompra")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorCompra())
            )
            .satisfies(a ->
                assertThat(a.getValorVenta())
                    .as("check valorVenta")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorVenta())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCotizacionUpdatableRelationshipsEquals(Cotizacion expected, Cotizacion actual) {
        assertThat(actual)
            .as("Verify Cotizacion relationships")
            .satisfies(a -> assertThat(a.getMoneda()).as("check moneda").isEqualTo(expected.getMoneda()));
    }
}
