package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstadoVentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoVentaAllPropertiesEquals(EstadoVenta expected, EstadoVenta actual) {
        assertEstadoVentaAutoGeneratedPropertiesEquals(expected, actual);
        assertEstadoVentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoVentaAllUpdatablePropertiesEquals(EstadoVenta expected, EstadoVenta actual) {
        assertEstadoVentaUpdatableFieldsEquals(expected, actual);
        assertEstadoVentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoVentaAutoGeneratedPropertiesEquals(EstadoVenta expected, EstadoVenta actual) {
        assertThat(actual)
            .as("Verify EstadoVenta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoVentaUpdatableFieldsEquals(EstadoVenta expected, EstadoVenta actual) {
        assertThat(actual)
            .as("Verify EstadoVenta relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoVentaUpdatableRelationshipsEquals(EstadoVenta expected, EstadoVenta actual) {
        // empty method
    }
}
