package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioAllPropertiesEquals(Inventario expected, Inventario actual) {
        assertInventarioAutoGeneratedPropertiesEquals(expected, actual);
        assertInventarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioAllUpdatablePropertiesEquals(Inventario expected, Inventario actual) {
        assertInventarioUpdatableFieldsEquals(expected, actual);
        assertInventarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioAutoGeneratedPropertiesEquals(Inventario expected, Inventario actual) {
        assertThat(actual)
            .as("Verify Inventario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioUpdatableFieldsEquals(Inventario expected, Inventario actual) {
        assertThat(actual)
            .as("Verify Inventario relevant properties")
            .satisfies(a -> assertThat(a.getFechaIngreso()).as("check fechaIngreso").isEqualTo(expected.getFechaIngreso()))
            .satisfies(a -> assertThat(a.getUbicacion()).as("check ubicacion").isEqualTo(expected.getUbicacion()))
            .satisfies(a -> assertThat(a.getEstadoInventario()).as("check estadoInventario").isEqualTo(expected.getEstadoInventario()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getDisponible()).as("check disponible").isEqualTo(expected.getDisponible()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getFechaReserva()).as("check fechaReserva").isEqualTo(expected.getFechaReserva()))
            .satisfies(a ->
                assertThat(a.getFechaVencimientoReserva())
                    .as("check fechaVencimientoReserva")
                    .isEqualTo(expected.getFechaVencimientoReserva())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventarioUpdatableRelationshipsEquals(Inventario expected, Inventario actual) {
        assertThat(actual)
            .as("Verify Inventario relationships")
            .satisfies(a -> assertThat(a.getVehiculo()).as("check vehiculo").isEqualTo(expected.getVehiculo()))
            .satisfies(a -> assertThat(a.getClienteReserva()).as("check clienteReserva").isEqualTo(expected.getClienteReserva()));
    }
}
