package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MarcaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaAllPropertiesEquals(Marca expected, Marca actual) {
        assertMarcaAutoGeneratedPropertiesEquals(expected, actual);
        assertMarcaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaAllUpdatablePropertiesEquals(Marca expected, Marca actual) {
        assertMarcaUpdatableFieldsEquals(expected, actual);
        assertMarcaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaAutoGeneratedPropertiesEquals(Marca expected, Marca actual) {
        assertThat(actual)
            .as("Verify Marca auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaUpdatableFieldsEquals(Marca expected, Marca actual) {
        assertThat(actual)
            .as("Verify Marca relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getPaisOrigen()).as("check paisOrigen").isEqualTo(expected.getPaisOrigen()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaUpdatableRelationshipsEquals(Marca expected, Marca actual) {
        // empty method
    }
}
