package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetodoPagoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetodoPagoAllPropertiesEquals(MetodoPago expected, MetodoPago actual) {
        assertMetodoPagoAutoGeneratedPropertiesEquals(expected, actual);
        assertMetodoPagoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetodoPagoAllUpdatablePropertiesEquals(MetodoPago expected, MetodoPago actual) {
        assertMetodoPagoUpdatableFieldsEquals(expected, actual);
        assertMetodoPagoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetodoPagoAutoGeneratedPropertiesEquals(MetodoPago expected, MetodoPago actual) {
        assertThat(actual)
            .as("Verify MetodoPago auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetodoPagoUpdatableFieldsEquals(MetodoPago expected, MetodoPago actual) {
        assertThat(actual)
            .as("Verify MetodoPago relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a ->
                assertThat(a.getRequiereReferencia()).as("check requiereReferencia").isEqualTo(expected.getRequiereReferencia())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetodoPagoUpdatableRelationshipsEquals(MetodoPago expected, MetodoPago actual) {
        // empty method
    }
}
