package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonedaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonedaAllPropertiesEquals(Moneda expected, Moneda actual) {
        assertMonedaAutoGeneratedPropertiesEquals(expected, actual);
        assertMonedaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonedaAllUpdatablePropertiesEquals(Moneda expected, Moneda actual) {
        assertMonedaUpdatableFieldsEquals(expected, actual);
        assertMonedaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonedaAutoGeneratedPropertiesEquals(Moneda expected, Moneda actual) {
        assertThat(actual)
            .as("Verify Moneda auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonedaUpdatableFieldsEquals(Moneda expected, Moneda actual) {
        assertThat(actual)
            .as("Verify Moneda relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getSimbolo()).as("check simbolo").isEqualTo(expected.getSimbolo()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonedaUpdatableRelationshipsEquals(Moneda expected, Moneda actual) {
        // empty method
    }
}
