package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MotorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMotorAllPropertiesEquals(Motor expected, Motor actual) {
        assertMotorAutoGeneratedPropertiesEquals(expected, actual);
        assertMotorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMotorAllUpdatablePropertiesEquals(Motor expected, Motor actual) {
        assertMotorUpdatableFieldsEquals(expected, actual);
        assertMotorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMotorAutoGeneratedPropertiesEquals(Motor expected, Motor actual) {
        assertThat(actual)
            .as("Verify Motor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMotorUpdatableFieldsEquals(Motor expected, Motor actual) {
        assertThat(actual)
            .as("Verify Motor relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getCilindradaCc()).as("check cilindradaCc").isEqualTo(expected.getCilindradaCc()))
            .satisfies(a -> assertThat(a.getCilindroCant()).as("check cilindroCant").isEqualTo(expected.getCilindroCant()))
            .satisfies(a -> assertThat(a.getPotenciaHp()).as("check potenciaHp").isEqualTo(expected.getPotenciaHp()))
            .satisfies(a -> assertThat(a.getTurbo()).as("check turbo").isEqualTo(expected.getTurbo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMotorUpdatableRelationshipsEquals(Motor expected, Motor actual) {
        assertThat(actual)
            .as("Verify Motor relationships")
            .satisfies(a -> assertThat(a.getCombustible()).as("check combustible").isEqualTo(expected.getCombustible()));
    }
}
