package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class Prueba1Asserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrueba1AllPropertiesEquals(Prueba1 expected, Prueba1 actual) {
        assertPrueba1AutoGeneratedPropertiesEquals(expected, actual);
        assertPrueba1AllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrueba1AllUpdatablePropertiesEquals(Prueba1 expected, Prueba1 actual) {
        assertPrueba1UpdatableFieldsEquals(expected, actual);
        assertPrueba1UpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrueba1AutoGeneratedPropertiesEquals(Prueba1 expected, Prueba1 actual) {
        assertThat(actual)
            .as("Verify Prueba1 auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrueba1UpdatableFieldsEquals(Prueba1 expected, Prueba1 actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrueba1UpdatableRelationshipsEquals(Prueba1 expected, Prueba1 actual) {
        // empty method
    }
}
