package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoComprobanteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoComprobanteAllPropertiesEquals(TipoComprobante expected, TipoComprobante actual) {
        assertTipoComprobanteAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoComprobanteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoComprobanteAllUpdatablePropertiesEquals(TipoComprobante expected, TipoComprobante actual) {
        assertTipoComprobanteUpdatableFieldsEquals(expected, actual);
        assertTipoComprobanteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoComprobanteAutoGeneratedPropertiesEquals(TipoComprobante expected, TipoComprobante actual) {
        assertThat(actual)
            .as("Verify TipoComprobante auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoComprobanteUpdatableFieldsEquals(TipoComprobante expected, TipoComprobante actual) {
        assertThat(actual)
            .as("Verify TipoComprobante relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoComprobanteUpdatableRelationshipsEquals(TipoComprobante expected, TipoComprobante actual) {
        // empty method
    }
}
