package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoCajaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCajaAllPropertiesEquals(TipoCaja expected, TipoCaja actual) {
        assertTipoCajaAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoCajaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCajaAllUpdatablePropertiesEquals(TipoCaja expected, TipoCaja actual) {
        assertTipoCajaUpdatableFieldsEquals(expected, actual);
        assertTipoCajaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCajaAutoGeneratedPropertiesEquals(TipoCaja expected, TipoCaja actual) {
        assertThat(actual)
            .as("Verify TipoCaja auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCajaUpdatableFieldsEquals(TipoCaja expected, TipoCaja actual) {
        assertThat(actual)
            .as("Verify TipoCaja relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCajaUpdatableRelationshipsEquals(TipoCaja expected, TipoCaja actual) {
        // empty method
    }
}
