package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoVehiculoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVehiculoAllPropertiesEquals(TipoVehiculo expected, TipoVehiculo actual) {
        assertTipoVehiculoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoVehiculoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVehiculoAllUpdatablePropertiesEquals(TipoVehiculo expected, TipoVehiculo actual) {
        assertTipoVehiculoUpdatableFieldsEquals(expected, actual);
        assertTipoVehiculoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVehiculoAutoGeneratedPropertiesEquals(TipoVehiculo expected, TipoVehiculo actual) {
        assertThat(actual)
            .as("Verify TipoVehiculo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVehiculoUpdatableFieldsEquals(TipoVehiculo expected, TipoVehiculo actual) {
        assertThat(actual)
            .as("Verify TipoVehiculo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoVehiculoUpdatableRelationshipsEquals(TipoVehiculo expected, TipoVehiculo actual) {
        // empty method
    }
}
