package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TraccionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraccionAllPropertiesEquals(Traccion expected, Traccion actual) {
        assertTraccionAutoGeneratedPropertiesEquals(expected, actual);
        assertTraccionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraccionAllUpdatablePropertiesEquals(Traccion expected, Traccion actual) {
        assertTraccionUpdatableFieldsEquals(expected, actual);
        assertTraccionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraccionAutoGeneratedPropertiesEquals(Traccion expected, Traccion actual) {
        assertThat(actual)
            .as("Verify Traccion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraccionUpdatableFieldsEquals(Traccion expected, Traccion actual) {
        assertThat(actual)
            .as("Verify Traccion relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraccionUpdatableRelationshipsEquals(Traccion expected, Traccion actual) {
        // empty method
    }
}
