package com.concesionaria.app.domain;

import static com.concesionaria.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VehiculoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAllPropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertVehiculoAutoGeneratedPropertiesEquals(expected, actual);
        assertVehiculoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAllUpdatablePropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertVehiculoUpdatableFieldsEquals(expected, actual);
        assertVehiculoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAutoGeneratedPropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(actual)
            .as("Verify Vehiculo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoUpdatableFieldsEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(actual)
            .as("Verify Vehiculo relevant properties")
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaFabricacion()).as("check fechaFabricacion").isEqualTo(expected.getFechaFabricacion()))
            .satisfies(a -> assertThat(a.getKm()).as("check km").isEqualTo(expected.getKm()))
            .satisfies(a -> assertThat(a.getPatente()).as("check patente").isEqualTo(expected.getPatente()))
            .satisfies(a ->
                assertThat(a.getPrecio()).as("check precio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrecio())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoUpdatableRelationshipsEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(actual)
            .as("Verify Vehiculo relationships")
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getMotor()).as("check motor").isEqualTo(expected.getMotor()))
            .satisfies(a -> assertThat(a.getTipoVehiculo()).as("check tipoVehiculo").isEqualTo(expected.getTipoVehiculo()));
    }
}
