package com.concesionaria.app.domain;

import static com.concesionaria.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAllPropertiesEquals(Venta expected, Venta actual) {
        assertVentaAutoGeneratedPropertiesEquals(expected, actual);
        assertVentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAllUpdatablePropertiesEquals(Venta expected, Venta actual) {
        assertVentaUpdatableFieldsEquals(expected, actual);
        assertVentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAutoGeneratedPropertiesEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaUpdatableFieldsEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a ->
                assertThat(a.getCotizacion())
                    .as("check cotizacion")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCotizacion())
            )
            .satisfies(a ->
                assertThat(a.getImporteNeto())
                    .as("check importeNeto")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getImporteNeto())
            )
            .satisfies(a ->
                assertThat(a.getImpuesto()).as("check impuesto").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getImpuesto())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a ->
                assertThat(a.getPorcentajeImpuesto())
                    .as("check porcentajeImpuesto")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPorcentajeImpuesto())
            )
            .satisfies(a ->
                assertThat(a.getTotalPagado())
                    .as("check totalPagado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalPagado())
            )
            .satisfies(a -> assertThat(a.getSaldo()).as("check saldo").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSaldo()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaUpdatableRelationshipsEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getEstadoVenta()).as("check estadoVenta").isEqualTo(expected.getEstadoVenta()))
            .satisfies(a -> assertThat(a.getMoneda()).as("check moneda").isEqualTo(expected.getMoneda()));
    }
}
