package com.concesionaria.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VersionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersionAllPropertiesEquals(Version expected, Version actual) {
        assertVersionAutoGeneratedPropertiesEquals(expected, actual);
        assertVersionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersionAllUpdatablePropertiesEquals(Version expected, Version actual) {
        assertVersionUpdatableFieldsEquals(expected, actual);
        assertVersionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersionAutoGeneratedPropertiesEquals(Version expected, Version actual) {
        assertThat(actual)
            .as("Verify Version auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersionUpdatableFieldsEquals(Version expected, Version actual) {
        assertThat(actual)
            .as("Verify Version relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getAnioInicio()).as("check anioInicio").isEqualTo(expected.getAnioInicio()))
            .satisfies(a -> assertThat(a.getAnioFin()).as("check anioFin").isEqualTo(expected.getAnioFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVersionUpdatableRelationshipsEquals(Version expected, Version actual) {
        // empty method
    }
}
