export enum TipoMovimientoPago {
  PAGO_RECIBIDO = 'PAGO_RECIBIDO',
  ANTICIPO = 'ANTICIPO',
  SENA_RESERVA = 'SENA_RESERVA',
  DEVOLUCION = 'DEVOLUCION',
  ANULACION = 'ANULACION',
  AJUSTE = 'AJUSTE',
}
